# Site settings
title: DALI 2017 - Data Learning and Inference
permalink: "/:title.html"
# Include image banner file name below
banner: costa-adeje.jpg 
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: dali

baseurl: "/dali2017" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  dalimeeting
author:
  name: DALI
  
ghub:
  edit: true
  repository: dali2017

conference:
  draft: false
  hide_tentative: true
  instance: 3rd
  styling: Workshop on
  name: Data Learning and Inference
  short_name: DALI
  full_name: Data Learning and Inference
  venue: H10 Costa Adeje Palace
  location: Tenerife, Canary Islands
  year: 2017
  month: April
  dates:
  - 2017-04-18
  - 2017-04-19
  - 2017-04-20
  
  hosts:
  chairs:
  - type: General Chairs
    people: 
    - given: Zoubin
      family: Ghaharamani
      url: "http://mlg.eng.cam.ac.uk/zoubin/"
      institute: University of Cambridge
    - given: Bernhard
      family: Schölkopf
      url: "http://ei.is.tuebingen.mpg.de/person/bs"
      institute: MPI for Intelligent Systems Tübingen
  - type: Workshop Chair
    people:
    - given: Thomas
      family: Hofmann
      url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
      institute: ETH Zurich
  - type: Symposium Chair
    people:
    - given: Neil D.
      family: Lawrence
      url: "http://inverseprobability.com"
      institute: Amazon and University of Sheffield
  - type: Local Chairs
    people:
    - given: Pablo M.
      family: Olmos
      url: "http://www.tsc.uc3m.es/~olmos/"
      institute: "Universidad Carlos III de Madrid"
    - given: Isabel Valera
      url: "http://www.mpi-sws.org/~ivalera/"
      institute: "Max Planck Institute for Software Systems"
  - type: Assistants
    people:
    - given: Sabrina
      family: Nepozitek
      url: "http://www.da.inf.ethz.ch/people/SabrinaNepozitek/"
      institute: ETH Zurich
  - type: Steering Committee
    people:
    - given: Zoubin
      family: Ghaharamani
      url: "http://mlg.eng.cam.ac.uk/zoubin/"
      institute: University of Cambridge
    - given: Thomas
      family: Hofmann
      url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
      institute: ETH Zurich
    - given: Neil D.
      family: Lawrence
      url: "http://inverseprobability.com"
      institute: University of Sheffield
    - given: Bernhard
      family: Schölkopf
      positon: Chair
      url: "http://ei.is.tuebingen.mpg.de/person/bs"
      institute: MPI Tübingen
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
previous_meeting:
  name: DALI 2016
  url: "http://dalimeeting.org/dali2016/"
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting

future: true

# Build settings
markdown: kramdown
